server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=true&amp;serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    thymeleaf:
      prefix: classpath:/templates/  #prefix：指定模板所在的目录
      check-template-location: true  #check-tempate-location: 检查模板路径是否存在
      cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
      suffix: .html
      #encoding: UTF-8
      #content-type: text/html
      mode: HTML5

mybatis:
    mapper-locations: classpath:/mybatis/*.xml
    type-aliases-package: wangfengyu.demo.pojo

#showSql
logging:
  file:
    name: log/log.log
  level:
    root: info
    com.wangfengyu: debug
